# ============================================
# CURSOR RULES EXPORTER
# GOD-OPENCODE Feature 5 (multi-host portability)
# ============================================
# Converts an agents/<name>/AGENT.md into the .cursorrules schema so
# users on Cursor (or Windsurf/Aider) automatically pick up the same
# persona they would see inside OpenCode.
#
# Usage:
#   .\scripts\export-cursorrules.ps1 -Agent backend-engineer
#   .\scripts\export-cursorrules.ps1 -Agent backend-engineer -OutFile .cursorrules
#   .\scripts\export-cursorrules.ps1 -AllAgents -OutDir dist/cursorrules
#
# The Cursor schema wants:
#   ---                                  (frontmatter fence)
#   description: <one-line>
#   globs: *.ts,*.tsx                   (optional, defaults to all)
#   alwaysApply: false
#   ---                                  (frontmatter close)
#   <role + standards + skills body>
#
# Source schema (agents/<name>/AGENT.md):
#   # <name>
#   ## Role
#   ## Responsibilities
#   ## Standards
#   ## Skills
#
# Skill-line items under `## Skills` are written as plain Markdown bullets;
# Cursor does not parse them as imports, but matches them on intent.

[CmdletBinding()]
param(
    [string]$Agent,
    [string]$OutFile,
    [string]$OutDir,
    [switch]$AllAgents
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "shared-utils.ps1")

$Root = Get-ProjectRoot
$AgentsRoot = Join-Path $Root "agents"

# ============================================
# Helpers — declared as top-level siblings of the script body so they are
# reachable from any caller, from Pester tests, and from the script's main
# code path below. Nested function declarations inside Export-OneAgent are
# a real hazard (out-of-scope at call sites, invisible to introspection).
# ============================================

function Get-Section {
    # Pull a Markdown section by header name (e.g. "Role", "Standards").
    # Uses `(?ms)` so `.+?` matches across newlines — equivalent to the
    # `[\s\S]+?` character class but avoids the PowerShell parser trap
    # where `$([\s\S]...)` is interpreted as a type-access expression
    # (parser error: "Missing type name after '['").
    param(
        [Parameter(Mandatory)][string]$SrcBody,
        [Parameter(Mandatory)][string]$Header
    )
    $EscapedHeader = [regex]::Escape($Header)
    # Build the regex in two pieces so the PowerShell parser does not see a `$`
    # character immediately followed by `(` and try to interpret `$(.+?)` as a
    # subexpression that would invoke `.` as a cmdlet. Regex end-of-line anchor
    # `$` and the opening paren of the capture group must be kept separate.
    $Pattern = "(?ms)^##\s+" + $EscapedHeader + "\s*$" + "(.+?)(?=^##\s|\z)"
    $m = [regex]::Match($SrcBody, $Pattern)
    if ($m.Success) { return $m.Groups[1].Value.Trim() }
    return ""
}

function Export-OneAgent {
    param(
        [Parameter(Mandatory)][string]$AgentsRoot,
        [Parameter(Mandatory)][string]$AgentName,
        [Parameter(Mandatory)][string]$TargetPath
    )

    $Src = Join-Path $AgentsRoot "$AgentName\AGENT.md"
    if (!(Test-Path $Src)) {
        Write-Host "[ERR] agents/$AgentName/AGENT.md not found" -ForegroundColor Red
        return
    }

    $Body = Get-Content $Src -Raw
    if ([string]::IsNullOrWhiteSpace($Body)) {
        Write-Host "[ERR] agents/$AgentName/AGENT.md is empty" -ForegroundColor Red
        return
    }

    # Pull the H1. The pattern uses `(?m)` (multiline mode) so `^` matches the start
    # of any line, not just position 0 of the input string. Without `(?m)`, the pipe
    # through Select-String on a multi-line string only matches the very first line,
    # and `.Matches[0]` crashes with "Cannot index into a null array".
    $H1 = ([regex]::Match($Body, '(?m)^# (.+)$')).Groups[1].Value.Trim()

    $Role        = Get-Section -SrcBody $Body -Header "Role"
    $Responsib   = Get-Section -SrcBody $Body -Header "Responsibilities"
    $Standards   = Get-Section -SrcBody $Body -Header "Standards"
    $Skills      = Get-Section -SrcBody $Body -Header "Skills"

    $Description = if ($Role) {
        ($Role -split "`r?`n" | Select-Object -First 1).Trim()
    } else {
        "GOD-OPENCODE agent: $AgentName"
    }

    $Out = @()
    $Out += "---"
    $Out += "description: $Description"
    $Out += "globs: *"
    $Out += "alwaysApply: false"
    $Out += "source: god-opencode/agents/$AgentName/AGENT.md"
    $Out += "version: 1.3.0"
    $Out += "---"
    $Out += ""
    $Out += "# $H1 (exported from GOD-OPENCODE)"
    $Out += ""
    if ($Role)      { $Out += "## Role`n$Role`n" }
    if ($Responsib) { $Out += "## Responsibilities`n$Responsib`n" }
    if ($Standards) { $Out += "## Standards`n$Standards`n" }
    if ($Skills)    { $Out += "## Skills`n$Skills`n" }
    $Out += "## Notes"
    $Out += ""
    $Out += "> Auto-generated by `scripts/export-cursorrules.ps1`. Re-run from the GOD-OPENCODE repo to refresh after agent changes; do not hand-edit."
    $Out += ""

    $OutDir2 = Split-Path $TargetPath -Parent
    if ($OutDir2 -and !(Test-Path $OutDir2)) {
        New-Item -ItemType Directory -Path $OutDir2 -Force | Out-Null
    }

    Write-IfChanged -Path $TargetPath -Content ($Out -join "`n")
}

# ============================================
# Main script body
# ============================================

if (-not $Agent -and -not $AllAgents) {
    Write-Host "[ERR] Provide -Agent <name> or -AllAgents." -ForegroundColor Red
    exit 1
}

if ($AllAgents) {
    foreach ($a in (Get-ChildItem -Path $AgentsRoot -Directory)) {
        $Target = if ($OutDir) {
            Join-Path $OutDir "$($a.Name).cursorrules"
        } else {
            Join-Path $Root "$($a.Name).cursorrules"
        }
        Export-OneAgent -AgentsRoot $AgentsRoot -AgentName $a.Name -TargetPath $Target
    }
    exit 0
}

if (-not $OutFile) {
    $OutFile = if ($OutDir) {
        Join-Path $OutDir "$Agent.cursorrules"
    } else {
        Join-Path $Root "$Agent.cursorrules"
    }
}

Export-OneAgent -AgentsRoot $AgentsRoot -AgentName $Agent -TargetPath $OutFile
